// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cciioosucdrcdnebohag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNjaWlvb3N1Y2RyY2RuZWJvaGFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NTcxOTAsImV4cCI6MjA2MjEzMzE5MH0.kX3PjRewRjbiDyjfr_x5RtbuIufv-0oUuxxQkUWwgiA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);